name: Phonebook Deployment 

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  phonebook_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Bump version and push tag
        if: | 
          ( github.event_name == 'push' )
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false
      - name: Deployment
        if: |
          ( github.event_name == 'push' )
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "app-part11-phonebook"
            heroku_email: "juha.jylhaekoski@gmail.com"
            rollbackonhealthcheckfailed: true
